<?php
// Frases para mostrar al azar.
// Enlace: https://estilonext.com/frases-y-reflexiones/frases-positivas (usada)
//         https://estilonext.com/frases-y-reflexiones/frases-sabias    (posible usar)
//
//
$frases_sliders = [
  "Si puedes soñarlo, puedes hacerlo.",
  "La buena suerte se produce cuando la preparación se encuentra con la oportunidad.",
  "Del sufrimiento emergieron las almas más fuertes. Los caracteres sólidos tienen cicatrices.",
  "Aprendí que es mejor no preocuparse demasiado. Lo que llega es por algo, lo que se va… también.",
  "Los desafíos son los que hacen la vida interesante, y superarlos es lo que hace la vida significativa.",
  "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene.",
  "Estoy agradecido por todos los que me dijeron NO. Es gracias a ellos que estoy siendo yo mismo.",
  "Hay una fuerza motriz más poderosa que el vapor, la electricidad y la energía atómica: la voluntad.",
  "Seamos realistas y hagamos lo imposible.",
  "La paciencia es amarga, pero su fruto es dulce.",
  "Mi filosofía es que no sólo tú eres responsable de tu vida, pero haciendo lo mejor en este momento, nos ponemos en el mejor lugar para el momento siguiente.",
  "Si exagerásemos nuestras alegrías, como hacemos con nuestras penas, nuestros problemas perderían importancia.",
  "No juzgues cada día por la cosecha que has obtenido, sino por las semillas que has plantado.",
  "Nunca es demasiado tarde para ser lo que podría haber sido.",
  "Lo que no te mata te hace más fuerte.",
  "He fallado una y otra vez en mi vida. Esa es la razón principal de mi éxito.",
  "El éxito llega para todos aquellos que están ocupados buscándolo.",
  "La clave de tu futuro está escondida en tu vida diaria.",
  "El destino mezcla las cartas, pero nosotros las jugamos.",
  "El éxito de la vida no está en vencer siempre, sino en no darse por vencido nunca.",
  "Si no puedes parar de pensar en algo, NO PARES de trabajar para conseguirlo.",
  "Serás feliz dijo la vida, pero primero te haré fuerte.",
  "A veces se gana, a veces se aprende.",
  "La mejor manera de predecir el futuro es creándolo.",
  "Sigue tus sueños, llega a la meta y luego mira desde ahí a aquellos que te decían que tú no podías.",
  "La felicidad se puede hallar hasta en los momentos más oscuros, si somos capaces de usar bien la luz.",
  "Algún día diré “No fue fácil, pero lo logré”.",
  "Soy más fuerte que las excusas.",
  "La imperfección es un tipo de libertad.",
  "Vive de la forma en que deseas ser recordada.",
  "Trabaja duro y en silencio, y deja que tu éxito haga todo el ruido.",
  "No permitas que las mentes pequeñas te digan que tus sueños son demasiado grandes.",
  "Grande es aquel que para brillar no necesita apagar la luz de los demás.",
  "Hazlo con pasión, o no lo hagas.",
  "Dime que no puedo y tendré un motivo más para lograrlo.",
  "Hazlo. Van a criticarte igual.",
  "Muévete y el camino aparecerá.",
  "Tus sueños no tienen fecha de caducidad. Respira hondo y sigue.",
  "Sé genial, pero no malgastes tiempo demostrándolo.",
  "Nunca llueve eternamente.",
  "Una buena sonrisa puede ser el mejor ataque.",
  "No lo llames “mi sueño”, llámalo “mi plan.",
  "Yo puedo. Lo haré. Fin de la historia.",
  "El que puede cambiar sus pensamientos puede cambiar su destino.",
  "Cáete siete veces, pero levántate ocho.",
  "Aprende a sonreír en cualquier situación. Tómatelo como una oportunidad para expresar tu fortaleza.",
  "Mantén una mente positiva y ríete de todo.",
  "La vida no tiene mando a distancia. Levántate y cámbiala por tus propios medios.",
  "No hay fracaso, solo éxito inacabado.",
  "¡Alumbra el mañana con el hoy! Porque desde cada acto del presente construimos el futuro.",
  "Si te caíste ayer, levántate hoy.",
  "Donde otros vean luces, sé capaz de ver las estrellas.",
  "Incluso la noche más oscura terminará con la salida del sol.",
  "Hoy es el primer día del resto de nuestras vidas.",
  "Si miras el sol, no verás las sombras.",
  "Soy optimista. No parece muy útil ser cualquier otra cosa.",
  "El aprendizaje es un regalo, incluso cuando el dolor es tu maestro.",
  "Sé un fénix: Renace de tus propias cenizas.",
  "Hay una fuerza motriz más poderosa que el vapor, la electricidad y la energía atómica: la voluntad.",
  "Si la vida te da un limón, ¡haz una limonada!.",
  "Un diamante es sólo un trozo de carbón que soportó una presión extraordinaria.",
  "La mejor venganza es un éxito masivo.",
  "Cuando estés a punto de abandonar, recuerda porqué empezaste.",
  "No mires el reloj. Haz lo que él hace: Sigue adelante.",
  "Yo hago lo imposible. Lo posible lo hace cualquiera.",
  "Cuando te sientas triste, piensa lo felices que son otros que están mucho peor que tú.",
  "Si encuentras un camino sin obstáculos, probablemente no lleva a ningún lugar.",
  "Mira en el espejo… ésa es tu competencia.",
  "No tienes que ser grande para comenzar, pero tienes que comenzar para ser grande.",
  "Cada sueño comienza con un soñador: sigue soñando."
];

// Para el random
$frases_sliders_tam = count($frases_sliders);
if ($frases_sliders_tam > 0) {
  $frases_sliders_tam--;
}
